/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Logger */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     App
	 * Method:    print
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_amr_cp_App_print
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif