/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Logger */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    test
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_test
	(JNIEnv *, jobject);
	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    print
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_print
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    start
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_start
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    addPlayer
	 * Signature: (jstring)V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_addPlayer
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    findPlayer
	 * Signature: (jstring)V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_findPlayer
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    init
	 * Signature: (jstring,jstring)V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_initPlayer
	(JNIEnv *, jobject, jstring, jstring);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnName
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnNameQuestion
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnAge
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnStudy
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnVersion
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnGreeting
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    jstring
	 * Signature: ()jstring
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnGreetingQuestion
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    finish
	 * Signature: ()V
	 */
	JNIEXPORT jboolean JNICALL Java_portal_NPCNativePortal_returnCheckForNPCResponse
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    finish
	 * Signature: ()V
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnNPCResponseType
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    finish
	 * Signature: ()V
	 */
	JNIEXPORT jstring JNICALL Java_portal_NPCNativePortal_returnNPCResponseData
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    finish
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_clearNPCResponse
	(JNIEnv *, jobject);

	/*
	 * Class:     portal_NPCNativePortal
	 * Method:    finish
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_portal_NPCNativePortal_finish
	(JNIEnv *, jobject);

	

#ifdef __cplusplus
}
#endif
#endif