/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amr_cp_App */

#ifndef _Included_com_amr_cp_App
#define _Included_com_amr_cp_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amr_cp_App
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amr_cp_App_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
